[project]
name = "task-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shaiksiraj04", email = "jarismohammed7@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[project.scripts]
task-2 = "task_2:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
